sudo: false
language: go

go:
  - stable
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - 1.9.x

install:
  - go get -u golang.org/x/lint/golint

script:
  - golint ./v1
  - go test -v ./v1
